module.exports = function(grunt) {
  grunt.config.set("sass", {
    dev: {
      options: {
        compass: true
      },
      files: [
        {
          expand: true,
          cwd: "assets/styles/",
          src: ["importer.scss"],
          dest: ".tmp/public/css/",
          ext: ".css"
        },
        {
          expand: true,
          cwd: "assets-labfnp/sass/",
          src: ["importer.scss"],
          dest: ".tmp/public/css/labfnp/",
          ext: ".css"
        },
        {
          expand: true,
          cwd: "assets-b2b/sass/",
          src: ["importer.scss"],
          dest: ".tmp/public/css/b2b/",
          ext: ".css"
        } ,
        {
          expand: true,
          cwd: "assets-motorworld/sass/",
          src: ["importer.scss"],
          dest: ".tmp/public/css/motorworld/",
          ext: ".css"
        }
      ]
    }
  });
  grunt.loadNpmTasks("grunt-contrib-sass");
};

// ---
// generated by coffee-script 1.9.2
