import moment from 'moment';
import lodash from 'lodash';
describe('about SearchPecker Service.', function() {
  let searchPecker, defaultSearchPecker, searchPeckerId;
  before('建立 SearchPecker 資料', async (done) => {
    try {
      const defaultSearchPecker = {
        // id: '1',
        keywords: 'testKeywords',
        crawlerAgent: 'testCrawlerAgent',
        reportHtml: 'testReportHtml',
        reportImage: 'testReportImage',
        pageNo: '0',
        pageNoPrev: '0',
        pageNoWarn: '0',
        targetUrl: 'testTargetUrl',
        searchEngine: 'testSearchEngine'
      };
      // TODO searchPecker = SearchPecker.create
      const result = await SearchPecker.create(defaultSearchPecker);
      searchPeckerId = result.id;

      done();
    } catch (e) {
      done(e);
    }
  });

  it('根據 ID 更新 SearchPecker', async (done) => {
    try {
      const updateData = {
        keywords: 'updateKeywords',
        crawlerAgent: 'updateCrawlerAgent',
        reportHtml: 'updateReportHtml',
        reportImage: 'updateReportImage',
        pageNo: '1',
        pageNoPrev: '1',
        pageNoWarn: '1',
        targetUrl: 'updateTargetUrl',
        searchEngine: 'updateSearchEngine'
      }
      const searchPecker = await SearchPeckerService.update({ searchPeckerId, ...updateData});
      searchPecker.should.be.Object;
      searchPecker.keywords.should.be.eq(updateData.keywords);
      searchPecker.crawlerAgent.should.be.eq(updateData.crawlerAgent);
      searchPecker.reportHtml.should.be.eq(updateData.reportHtml);
      searchPecker.reportImage.should.be.eq(updateData.reportImage);
      searchPecker.pageNo.should.be.eq(updateData.pageNo);
      searchPecker.pageNoPrev.should.be.eq(updateData.pageNoPrev);
      searchPecker.pageNoWarn.should.be.eq(updateData.pageNoWarn);
      searchPecker.targetUrl.should.be.eq(updateData.targetUrl);
      searchPecker.searchEngine.should.be.eq(updateData.searchEngine);
      done();
    } catch (e) {
      done(e)
    }
  });

  describe.only('about SearchPecker demo data.', function() {
    it ('create', async(done) => {
      try {
        let list = [
          {
            "keywords": "生日禮物 送香水",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 22,
            "pageNo": 1.2,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",

          },
          {
            "keywords": "香水師課程",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 22,
            "pageNo": 2.2,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "自製 生日禮物",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 20,
            "pageNo": 2.6,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "客製化禮物",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 20,
            "pageNo": 0,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "手作香水",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 22,
            "pageNo": 1.8,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "香水 diy",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 20,
            "pageNo": 1.3,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "香水製作班",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 20,
            "pageNo": 1,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "送男朋友 香水",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 22,
            "pageNo": 1,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "自製禮物 男朋友",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 20,
            "pageNo": 2.3,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "+客制+禮物",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 18,
            "pageNo": 0,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "大地調香工作坊",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 21,
            "pageNo": 0,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "香料香水實驗室",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 19,
            "pageNo": 1,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "香薰香水 diy",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 20,
            "pageNo": 0,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "訂做香水",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 22,
            "pageNo": 0,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "+客製化+禮物",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 19,
            "pageNo": 0,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "做香水",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 22,
            "pageNo": 1.2,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "客制化香水",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 20,
            "pageNo": 0,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "客制 禮物",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 20,
            "pageNo": 3.1,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "客制禮物",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 19,
            "pageNo": 0,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "結婚禮物 客製",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 19,
            "pageNo": 0,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "製香水",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 20,
            "pageNo": 1.3,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "調香工作坊",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 19,
            "pageNo": 0,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "送男友 香水",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 22,
            "pageNo": 0,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "自製禮物 女朋友",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 20,
            "pageNo": 2.7,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "diy 香水配方",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 20,
            "pageNo": 1.3,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "自製香水店",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 20,
            "pageNo": 1,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "香水調香",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 22,
            "pageNo": 0,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "生日 送香水",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 22,
            "pageNo": 1.4,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "自制 香水",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 20,
            "pageNo": 1.4,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "香水製作 過程",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 20,
            "pageNo": 1.1,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "lfp 香水",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 19,
            "pageNo": 1.1,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "調香課程",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 23,
            "pageNo": 1.2,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "送女朋友 香水",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 22,
            "pageNo": 1,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "調香水",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 22,
            "pageNo": 1.1,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "送女友 香水",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 22,
            "pageNo": 0,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "香水 禮物",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 20,
            "pageNo": 2.2,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "調香師課程",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 23,
            "pageNo": 1.9,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "個人香水",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 20,
            "pageNo": 1.2,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "香水製作 方法",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 20,
            "pageNo": 1.2,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "韓國 diy香水",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 20,
            "pageNo": 0,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "調香水",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 22,
            "pageNo": 1.3,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "香水課",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 23,
            "pageNo": 1.3,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "個人化香水",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 20,
            "pageNo": 1,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "香水 調香",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 22,
            "pageNo": 1.2,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "自己調香水",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 22,
            "pageNo": 1,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "香水調製課程",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 23,
            "pageNo": 0,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "香水製作",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 20,
            "pageNo": 1.1,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "客製香水",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 20,
            "pageNo": 1.5,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "生日禮物 diy",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 18,
            "pageNo": 2.5,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "+客製+生日禮物",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 20,
            "pageNo": 3.6,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "結婚禮物 客製",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 20,
            "pageNo": 3,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "調配 香水",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 22,
            "pageNo": 1.2,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "調香 課程",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 23,
            "pageNo": 1.1,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "香水調配課程",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 23,
            "pageNo": 1,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "香水製造",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 20,
            "pageNo": 1.3,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "香水調製",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 22,
            "pageNo": 1.1,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "台中 香水實驗室",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 19,
            "pageNo": 0,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "客製化 禮物",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 20,
            "pageNo": 3.1,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "cyrano調香課程",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 21,
            "pageNo": 0,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "自製香水",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 20,
            "pageNo": 1.1,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "自調香水",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 22,
            "pageNo": 1,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "自己做香水",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 22,
            "pageNo": 1,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "送媽媽 香水",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 22,
            "pageNo": 1.8,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "自制香水 配方",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 20,
            "pageNo": 0,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "客製生日禮物",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 20,
            "pageNo": 0,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "調香配方",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 22,
            "pageNo": 1.1,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "香水調配師",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 22,
            "pageNo": 1.5,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "自己調配香水",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 22,
            "pageNo": 0,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "自製 生日禮物",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 20,
            "pageNo": 0,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "禮物 送香水",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 22,
            "pageNo": 1.4,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "+自製+生日禮物",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 20,
            "pageNo": 0,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "玫瑰 香水製作",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 20,
            "pageNo": 1,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "手工diy 禮物",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 20,
            "pageNo": 2.6,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "香氛美人手作課",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 21,
            "pageNo": 0,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "客製化香水",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 20,
            "pageNo": 1.1,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "創意禮物 diy",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 18,
            "pageNo": 3.1,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "香水課程",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 23,
            "pageNo": 1.3,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "lfp香料香水實驗室",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 19,
            "pageNo": 1,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "香水實驗室",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 19,
            "pageNo": 1,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
          {
            "keywords": "調香課",
            "crawlerAgent": "CargoRankBot-v1.0",
            "pageNoWarn": 23,
            "pageNo": 2,
            "targetUrl": "labfnp.com/*",
            "searchEngine": "www.google.com.tw",
            "reportHtml": "",
            "reportImage": "",
          },
        ]
        list = list.map((data) => {
          return {
            ...data,
            pageNo: ~~data.pageNo ? ~~data.pageNo: ~~data.pageNo + 1,
            pageNoPrev: ~~data.pageNo + 1,
          }
        })
        console.log(list);
        for (let data of list) {
          let result = await SearchPecker.create(data);
          let log = [{
            rank: _.random(10, 15),
            url: 'labfnp.com',
            recordDate: moment(new Date('2017/2/6')).format('YYYY/MM/DD'),
            SearchPeckerId: result.id
          },{
            rank: _.random(7, 13),
            url: 'labfnp.com',
            recordDate: moment(new Date('2017/2/7')).format('YYYY/MM/DD'),
            SearchPeckerId: result.id
          },{
            rank: _.random(5, 13),
            url: 'labfnp.com',
            recordDate: moment(new Date('2017/2/8')).format('YYYY/MM/DD'),
            SearchPeckerId: result.id
          },{
            rank: _.random(5, 10),
            url: 'labfnp.com',
            recordDate: moment(new Date('2017/2/9')).format('YYYY/MM/DD'),
            SearchPeckerId: result.id
          },{
            rank: _.random(6, 10),
            url: 'labfnp.com',
            recordDate: moment(new Date('2017/2/10')).format('YYYY/MM/DD'),
            SearchPeckerId: result.id
          },{
            rank: _.random(3, 7),
            url: 'labfnp.com',
            recordDate: moment(new Date('2017/2/11')).format('YYYY/MM/DD'),
            SearchPeckerId: result.id
          },{
            rank: _.random(3,7),
            url: 'labfnp.com',
            recordDate: moment(new Date('2017/2/12')).format('YYYY/MM/DD'),
            SearchPeckerId: result.id
          },{
            rank: _.random(2, 5),
            url: 'labfnp.com',
            recordDate: moment(new Date('2017/2/13')).format('YYYY/MM/DD'),
            SearchPeckerId: result.id
          },{
            rank: _.random(2, 5),
            url: 'labfnp.com',
            recordDate: moment(new Date('2017/2/14')).format('YYYY/MM/DD'),
            SearchPeckerId: result.id
          },{
            rank: _.random(1, 4),
            url: 'labfnp.com',
            recordDate: moment(new Date('2017/2/15')).format('YYYY/MM/DD'),
            SearchPeckerId: result.id
          },{
            rank: _.random(1, 4),
            url: 'labfnp.com',
            recordDate: moment(new Date('2017/2/16')).format('YYYY/MM/DD'),
            SearchPeckerId: result.id
          },{
            rank: _.random(2, 6),
            url: 'labfnp.com',
            recordDate: moment(new Date('2017/2/17')).format('YYYY/MM/DD'),
            SearchPeckerId: result.id
          },{
            rank: _.random(1, 3),
            url: 'labfnp.com',
            recordDate: moment(new Date('2017/2/18')).format('YYYY/MM/DD'),
            SearchPeckerId: result.id
          },{
            rank: _.random(1, 2),
            url: 'labfnp.com',
            recordDate: moment(new Date('2017/2/19')).format('YYYY/MM/DD'),
            SearchPeckerId: result.id
          },{
            rank: data.pageNo,
            url: 'labfnp.com',
            recordDate: moment(new Date('2017/2/20')).format('YYYY/MM/DD'),
            SearchPeckerId: result.id
          }]
          await SearchPeckerLog.bulkCreate(log);
        }
        done();
      } catch (e) {
        done(e);
      }
    })
  });


});
