import moment from 'moment';
import lodash from 'lodash';

module.exports.init = async () => {
  try {

    const isDevMode = sails.config.environment === 'development';
    const isDropMode = sails.config.models.migrate == 'drop';

    if (isDevMode && isDropMode) {
      // let searchPeckerData = [
      //   {
      //     keywords: '客製化香水 調香 香水 實驗室',
      //     crawlerAgent: 'CargoSearchBot-v.10',
      //     reportHtml: 'crawlerAgent/google/reault/html/report.html',
      //     reportImage: '/assets/labfnp/img/searchscreentshot_google.png',
      //     pageNo: '1',
      //     pageNoPrev: '1',
      //     pageNoWarn: '5',
      //     targetUrl: 'labfnp.com',
      //     searchEngine: 'www.google.com.tw'
      //   }, {
      //     keywords: '客製化香水 調香 香水 實驗室',
      //     crawlerAgent: 'CargoSearchBot-v.10',
      //     reportHtml: 'crawlerAgent/bing/reault/html/report.html',
      //     reportImage: '/assets/labfnp/img/searchscreentshot_bing.png',
      //     pageNo: '1',
      //     pageNoPrev: '1',
      //     pageNoWarn: '5',
      //     targetUrl: 'labfnp.com',
      //     searchEngine: 'www.bing.com'
      //   }, {
      //     keywords: '客製化香水 調香 香水 實驗室',
      //     crawlerAgent: 'CargoSearchBot-v.10',
      //     reportHtml: 'crawlerAgent/yahoo/reault/html/report.html',
      //     reportImage: '/assets/labfnp/img/searchscreentshot_yahoo.png',
      //     pageNo: '1',
      //     pageNoPrev: '1',
      //     pageNoWarn: '5',
      //     targetUrl: 'labfnp.com',
      //     searchEngine: 'tw.yahoo.com'
      //   }, {
      //     keywords: '客製化香水 調香 香水 實驗室',
      //     crawlerAgent: 'CargoSearchBot-v.10',
      //     reportHtml: 'crawlerAgent/baidu/reault/html/report.html',
      //     reportImage: '/assets/labfnp/img/searchscreentshot_baidu.png',
      //     pageNo: '1',
      //     pageNoPrev: '1',
      //     pageNoWarn: '5',
      //     targetUrl: 'labfnp.com',
      //     searchEngine: 'www.baidu.com'
      //   }, {
      //     keywords: 'DIY 香水',
      //     crawlerAgent: 'CargoSearchBot-v.10',
      //     reportHtml: 'crawlerAgent/baidu/reault/html/report.html',
      //     reportImage: '/assets/labfnp/img/searchscreentshot_google2.png',
      //     pageNo: '2',
      //     pageNoPrev: '2',
      //     pageNoWarn: '5',
      //     targetUrl: 'labfnp.com',
      //     searchEngine: 'google.com'
      //   }, {
      //     keywords: '自製 香水',
      //     crawlerAgent: 'CargoSearchBot-v.10',
      //     reportHtml: 'crawlerAgent/baidu/reault/html/report.html',
      //     reportImage: '/assets/labfnp/img/searchscreentshot_google3.png',
      //     pageNo: '2',
      //     pageNoPrev: '3',
      //     pageNoWarn: '5',
      //     targetUrl: 'labfnp.com',
      //     searchEngine: 'google.com'
      //   }
      // ];
      // await SearchPecker.bulkCreate(searchPeckerData);
      let list = [
        {
          "keywords": "生日禮物 送香水",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 22,
          "pageNo": 1.2,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",

        },
        {
          "keywords": "香水師課程",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 22,
          "pageNo": 2.2,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "自製 生日禮物",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 20,
          "pageNo": 2.6,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "客製化禮物",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 20,
          "pageNo": 0,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "手作香水",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 22,
          "pageNo": 1.8,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "香水 diy",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 20,
          "pageNo": 1.3,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "香水製作班",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 20,
          "pageNo": 1,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "送男朋友 香水",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 22,
          "pageNo": 1,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "自製禮物 男朋友",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 20,
          "pageNo": 2.3,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "+客制+禮物",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 18,
          "pageNo": 0,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "大地調香工作坊",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 21,
          "pageNo": 0,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "香料香水實驗室",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 19,
          "pageNo": 1,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "香薰香水 diy",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 20,
          "pageNo": 0,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "訂做香水",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 22,
          "pageNo": 0,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "+客製化+禮物",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 19,
          "pageNo": 0,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "做香水",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 22,
          "pageNo": 1.2,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "客制化香水",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 20,
          "pageNo": 0,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "客制 禮物",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 20,
          "pageNo": 3.1,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "客制禮物",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 19,
          "pageNo": 0,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "結婚禮物 客製",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 19,
          "pageNo": 0,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "製香水",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 20,
          "pageNo": 1.3,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "調香工作坊",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 19,
          "pageNo": 0,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "送男友 香水",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 22,
          "pageNo": 0,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "自製禮物 女朋友",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 20,
          "pageNo": 2.7,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "diy 香水配方",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 20,
          "pageNo": 1.3,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "自製香水店",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 20,
          "pageNo": 1,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "香水調香",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 22,
          "pageNo": 0,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "生日 送香水",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 22,
          "pageNo": 1.4,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "自制 香水",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 20,
          "pageNo": 1.4,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "香水製作 過程",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 20,
          "pageNo": 1.1,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "lfp 香水",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 19,
          "pageNo": 1.1,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "調香課程",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 23,
          "pageNo": 1.2,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "送女朋友 香水",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 22,
          "pageNo": 1,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "調香水",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 22,
          "pageNo": 1.1,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "送女友 香水",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 22,
          "pageNo": 0,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "香水 禮物",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 20,
          "pageNo": 2.2,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "調香師課程",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 23,
          "pageNo": 1.9,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "個人香水",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 20,
          "pageNo": 1.2,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "香水製作 方法",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 20,
          "pageNo": 1.2,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "韓國 diy香水",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 20,
          "pageNo": 0,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "調香水",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 22,
          "pageNo": 1.3,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "香水課",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 23,
          "pageNo": 1.3,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "個人化香水",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 20,
          "pageNo": 1,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "香水 調香",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 22,
          "pageNo": 1.2,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "自己調香水",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 22,
          "pageNo": 1,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "香水調製課程",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 23,
          "pageNo": 0,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "香水製作",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 20,
          "pageNo": 1.1,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "客製香水",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 20,
          "pageNo": 1.5,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "生日禮物 diy",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 18,
          "pageNo": 2.5,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "+客製+生日禮物",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 20,
          "pageNo": 3.6,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "結婚禮物 客製",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 20,
          "pageNo": 3,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "調配 香水",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 22,
          "pageNo": 1.2,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "調香 課程",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 23,
          "pageNo": 1.1,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "香水調配課程",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 23,
          "pageNo": 1,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "香水製造",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 20,
          "pageNo": 1.3,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "香水調製",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 22,
          "pageNo": 1.1,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "台中 香水實驗室",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 19,
          "pageNo": 0,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "客製化 禮物",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 20,
          "pageNo": 3.1,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "cyrano調香課程",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 21,
          "pageNo": 0,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "自製香水",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 20,
          "pageNo": 1.1,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "自調香水",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 22,
          "pageNo": 1,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "自己做香水",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 22,
          "pageNo": 1,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "送媽媽 香水",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 22,
          "pageNo": 1.8,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "自制香水 配方",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 20,
          "pageNo": 0,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "客製生日禮物",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 20,
          "pageNo": 0,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "調香配方",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 22,
          "pageNo": 1.1,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "香水調配師",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 22,
          "pageNo": 1.5,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "自己調配香水",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 22,
          "pageNo": 0,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "自製 生日禮物",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 20,
          "pageNo": 0,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "禮物 送香水",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 22,
          "pageNo": 1.4,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "+自製+生日禮物",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 20,
          "pageNo": 0,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "玫瑰 香水製作",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 20,
          "pageNo": 1,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "手工diy 禮物",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 20,
          "pageNo": 2.6,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "香氛美人手作課",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 21,
          "pageNo": 0,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "客製化香水",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 20,
          "pageNo": 1.1,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "創意禮物 diy",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 18,
          "pageNo": 3.1,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "香水課程",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 23,
          "pageNo": 1.3,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "lfp香料香水實驗室",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 19,
          "pageNo": 1,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "香水實驗室",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 19,
          "pageNo": 1,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
        {
          "keywords": "調香課",
          "crawlerAgent": "CargoRankBot-v1.0",
          "pageNoWarn": 23,
          "pageNo": 2,
          "targetUrl": "labfnp.com/*",
          "searchEngine": "www.google.com.tw",
          "reportHtml": "",
          "reportImage": "",
        },
      ]
      list = list.map((data) => {
        return {
          ...data,
          pageNo: ~~data.pageNo ? ~~data.pageNo: ~~data.pageNo + 1,
          pageNoPrev: ~~data.pageNo + 1,
        }
      })
      console.log(list);
      for (let data of list) {
        let result = await SearchPecker.create(data);
        let log = [{
          rank: _.random(10, 15),
          url: 'labfnp.com',
          recordDate: moment(new Date('2017/2/6')).format('YYYY-MM-DD'),
          SearchPeckerId: result.id
        },{
          rank: _.random(7, 13),
          url: 'labfnp.com',
          recordDate: moment(new Date('2017/2/7')).format('YYYY-MM-DD'),
          SearchPeckerId: result.id
        },{
          rank: _.random(5, 13),
          url: 'labfnp.com',
          recordDate: moment(new Date('2017/2/8')).format('YYYY-MM-DD'),
          SearchPeckerId: result.id
        },{
          rank: _.random(5, 10),
          url: 'labfnp.com',
          recordDate: moment(new Date('2017/2/9')).format('YYYY-MM-DD'),
          SearchPeckerId: result.id
        },{
          rank: _.random(6, 10),
          url: 'labfnp.com',
          recordDate: moment(new Date('2017/2/10')).format('YYYY-MM-DD'),
          SearchPeckerId: result.id
        },{
          rank: _.random(3, 7),
          url: 'labfnp.com',
          recordDate: moment(new Date('2017/2/11')).format('YYYY-MM-DD'),
          SearchPeckerId: result.id
        },{
          rank: _.random(3,7),
          url: 'labfnp.com',
          recordDate: moment(new Date('2017/2/12')).format('YYYY-MM-DD'),
          SearchPeckerId: result.id
        },{
          rank: _.random(2, 5),
          url: 'labfnp.com',
          recordDate: moment(new Date('2017/2/13')).format('YYYY-MM-DD'),
          SearchPeckerId: result.id
        },{
          rank: _.random(2, 5),
          url: 'labfnp.com',
          recordDate: moment(new Date('2017/2/14')).format('YYYY-MM-DD'),
          SearchPeckerId: result.id
        },{
          rank: _.random(1, 4),
          url: 'labfnp.com',
          recordDate: moment(new Date('2017/2/15')).format('YYYY-MM-DD'),
          SearchPeckerId: result.id
        },{
          rank: _.random(1, 4),
          url: 'labfnp.com',
          recordDate: moment(new Date('2017/2/16')).format('YYYY-MM-DD'),
          SearchPeckerId: result.id
        },{
          rank: _.random(2, 6),
          url: 'labfnp.com',
          recordDate: moment(new Date('2017/2/17')).format('YYYY-MM-DD'),
          SearchPeckerId: result.id
        },{
          rank: _.random(1, 3),
          url: 'labfnp.com',
          recordDate: moment(new Date('2017/2/18')).format('YYYY-MM-DD'),
          SearchPeckerId: result.id
        },{
          rank: _.random(1, 2),
          url: 'labfnp.com',
          recordDate: moment(new Date('2017/2/19')).format('YYYY-MM-DD'),
          SearchPeckerId: result.id
        },{
          rank: data.pageNo,
          url: 'labfnp.com',
          recordDate: moment(new Date('2017/2/20')).format('YYYY-MM-DD'),
          SearchPeckerId: result.id
        }]
        await SearchPeckerLog.bulkCreate(log);
      }
    }

  } catch (e) {
    console.error(e);
  }
};
